<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-01T02:22:58+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
