<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-01T02:35:41+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      seo.url_rewriting
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1506824585,
        'latest_version' => '8.2.1',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
