<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-10-01T02:35:41+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_url_alternative
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'new company name',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
            ],
        ],
    ],
];
